from random import randint
import datetime
import random
import os
import sys
import time
##By: MS40
##t.m:@ms4010
##meu pix: maycongg486@gmail.com

#COLORES
rojo = '\033[31;1m'
azul = '\033[34;1m'
verde = '\033[32;1m'
amarillo = '\033[33;1m'
morado = '\033[35;1m'
celeste = '\033[36;1m'
plomo = '\033[30;1m'
close = '\033[0m'

os.system ("toilet -f big 'BEM VINDO' -F gay | lolcat")
print(amarillo)
nick = str(input(' COLOQUE SEU NICK  : '))
os.system("clear")
os.system ("toilet -f big '★ MS40★' -F gay | lolcat")
os.system ("toilet -f big '★KUROKO★' -F gay | lolcat")
time.sleep(3)
os.system("clear")
os.system ("toilet -f big 'BLACKCCV8' -F gay | lolcat")
print("\n\033[33;1m OLÁ \033[31;1m★",nick,"★\033[33;1m BEM VINDO AO BLACKCPF \n  FERRAMENTO VOLTADO A CC, GERADORES E BINS\n")
print("\033[31;1m         MEU CANAL DO TELEGRAM: MS40_canal \033[32;1m")
print("\033[34;1m         CRIADO POR MS40 \033[32;1m")
print("MEU PIX: maycongg486@gmail.com ")
print('--------------------------------------------------------')
time.sleep(1)

s = True
n = False
list = [2022, 2023, 2024, 2025, 2026, 2027]
list2 = [1982, 1998, 2000, 2002, 2004, 2006,1981,2001,1988,1978,1997,1990,1971,1986,1976,1994,1983,1992,1991,1867,1981,1992]
NOMES = [
    "Aaron",
    "Abel",
    "Abelardo",
    "Abelino",
    "Abiel",
    "Abiezer",
    "Abílio",
    "Abner",
    "Abraão",
    "Acácio",
    "Adailton",
    "Adair",
    "Adalberto",
    "Adalgiso",
    "Adalício",
    "Adalmir",
    "Adalto",
    "Adam",
    "Adamastor",
    "Adamor",
    "Adão",
    "Adeci",
    "Adeildo",
    "Adelair",
    "Adélcio",
    "Adelino",
    "Adélio",
    "Adelson",
    "Ademar",
    "Ademilson",
    "Ademir",
    "Aderbal",
    "Adérito",
    "Adilson",
    "Admilson",
    "Adolfo",
    "Adonai",
    "Adonis",
    "Adónis",
    "Adrian",
    "Adriano",
    "Adriel",
    "Aécio",
    "Afonso",
    "Afrânio",
    "Agenor",
    "Ageo",
    "Agipino",
    "Agnaldo",
    "Agnelo",
    "Agostinho",
    "Aguinaldo",
    "Ailton",
    "Aires",
    "Airton",
    "Aitor",
    "Alair",
    "Alaôr",
    "Alarico",
    "Albano",
    "Albertino",
    "Albino",
    "Alcides",
    "Alcindo",
    "Aldair",
    "Aldemir",
    "Aldenor",
    "Aldo",
    "Alejandro",
    "Alessandro",
    "Alex",
    "Alexandrino",
    "Alexandro",
    "Aléxio",
    "Alfredo",
    "Alípio",
    "Alírio",
    "Alison",
    "Allan",
    "Almerindo",
    "Almir",
    "Aloísio",
    "Alonzo",
    "Altino",
    "Aluísio",
    "Alvantino",
    "Alvino",
    "Amadeo",
    "Amândio",
    "Amarildo",
    "Amauri",
    "Amaury",
    "Ambrósio",
    "Américo",
    "Amílcar",
    "Amilton",
    "Amir",
    "Ananias",
    "Andersen",
    "Anderson",
    "Ândreo",
    "Andrés",
    "Anésio",
    "Angélico",
    "Ângelo",
    "Aníbal",
    "Anísio",
    "Anselmo",
    "Antenor",
    "Antero",
    "Anthony",
    "Apollo",
    "Apolo",
    "Aprígio",
    "Aquiles",
    "Arcanjo",
    "Aristeu",
    "Aristides",
    "Armando",
    "Armindo",
    "Arnaldo",
    "Arthur",
    "Arturo",
    "Ary",
    "Asher",
    "Assis",
    "Ataíde",
    "Athos",
    "Átila",
    "Atlas",
    "Aureliano",
    "Aurelino",
    "Aurélio",
    "Aurino",
    "Ayrton",
    "Balbino",
    "Balduíno",
    "Baltasar",
    "Baltazar",
    "Barnabé",
    "Bartolomeu",
    "Basileu",
    "Basílio",
    "Batista",
    "Belarmino",
    "Belchior",
    "Belisário",
    "Belmiro",
    "Bendito",
    "Benedito",
    "Benito",
    "Benjamin",
    "Beto",
    "Bill",
    "Boanerges",
    "Bob",
    "Bonifácio",
    "Bóris",
    "Bosco",
    "Brandon",
    "Bruce",
    "Bryan",
    "Byron",
    "Cacildo",
    "Cadú",
    "Cael",
    "Caíco",
    "Caíque",
    "Calazan",
    "Calisto",
    "Calixto",
    "Calvin",
    "Camilo",
    "Cândido",
    "Canuto",
    "Casimiro",
    "Cassiano",
    "Cássio",
    "Castiel",
    "Cauã",
    "Cauê",
    "Celestino",
    "Celso",
    "César",
    "Charles",
    "Christian",
    "Christian",
    "Christopher",
    "Cirilo",
    "Ciro",
    "Cláudio",
    "Claus",
    "Clayton",
    "Clementino",
    "Clodomiro",
    "Clovis",
    "Clóvis",
    "Conrad",
    "Constantin",
    "Constantino",
    "Cosme",
    "Cristiano",
    "Cristóvão",
    "Cursino",
    "Custódio",
    "Dácio",
    "Dagoberto",
    "Dalmo",
    "Dalton",
    "Danilo",
    "Dante",
    "Dárcio",
    "Darius",
    "Deivid",
    "Delfino",
    "Delmar",
    "Demétrio",
    "Denis",
    "Denzel",
    "Derik",
    "Didier",
    "Dimas",
    "Dinis",
    "Diniz",
    "Dino",
    "Diógenes",
    "Dionísio",
    "Djalma",
    "Dom",
    "Domênico",
    "Dominic",
    "Donatello",
    "Donatílio",
    "Donato",
    "Donizete",
    "Douglas",
    "Douglas",
    "Durval",
    "Dylan",
    "Ed",
    "Éder",
    "Ederson",
    "Edivaldo",
    "Edmilson",
    "Edmir",
    "Edson",
    "Eliezer",
    "Élio",
    "Eliseo",
    "Eliseu",
    "Elísio",
    "Élton",
    "Emanuel",
    "Emaús",
    "Emerson",
    "Emílio",
    "Ênio",
    "Enrico",
    "Enrique",
    "Erasmo",
    "Erasmus",
    "Eriberto",
    "Erik",
    "Ernesto",
    "Esdras",
    "Eugénio",
    "Eurico",
    "Evaldo",
    "Evandro",
    "Evelásio",
    "Expedito",
    "Ezekiel",
    "Fabiano",
    "Faustino",
    "Fausto",
    "Felipe",
    "Felisberto",
    "Felismino",
    "Félix",
    "Ferdinand",
    "Ferdinando",
    "Fernando",
    "Fernão",
    "Firmino",
    "Flávio",
    "Florêncio",
    "Florentino",
    "Floriano",
    "Fortunato",
    "Francesco",
    "Francis",
    "Franco",
    "Frank",
    "Franklin",
    "Gael",
    "Galdino",
    "Galeno",
    "Galileu",
    "Gastão",
    "Gaudêncio",
    "Genaro",
    "Genésio",
    "Geovani",
    "Geraldo",
    "Germano",
    "Gerson",
    "Giancarlos",
    "Giani",
    "Gianluca",
    "Gilberto",
    "Gilmar",
    "Gilmar",
    "Gilson",
    "Giuseppe",
    "Glauco",
    "Golias",
    "Graciano",
    "Gregório",
    "Gualter",
    "Guarani",
    "Gumersindo",
    "Guy",
    "Haroldo",
    "Hélder",
    "Hélio",
    "Henry",
    "Herbert",
    "Hermano",
    "Hernâni",
    "Horácio",
    "Humberto",
    "Ike",
    "Irineu",
    "Isaías",
    "Isidoro",
    "Israel",
    "Ítalo",
    "Itamar",
    "Ivaldo",
    "Ivandro",
    "Ivanildo",
    "Jacinto",
    "Jack",
    "Jackson",
    "Jader",
    "Jadiel",
    "Jadir",
    "Jair",
    "Jairo",
    "Jamal",
    "Jamil",
    "Jandir",
    "Janilson",
    "Januário",
    "Jarbas",
    "Jason",
    "Jason",
    "Javier",
    "Jean",
    "Jefferson",
    "Jeremias",
    "Jessé",
    "Jessie",
    "Jessiel",
    "Jesualdo",
    "Jesus",
    "Joab",
    "Joelson",
    "Jofre",
    "Johnny",
    "Johnson",
    "Jonas",
    "Jonatã",
    "Josélio",
    "Joshua",
    "Josias",
    "Josué",
    "Juan",
    "Juliano",
    "Julião",
    "Júlio",
    "Júnior",
    "Jurandir",
    "Juvenal",
    "Kaique",
    "Kauã",
    "Kauan",
    "Kawan",
    "Kelvin",
    "Kennedy",
    "Klaus",
    "Kleber",
    "Lael",
    "Laerte",
    "Laertes",
    "Lauro",
    "Leon",
    "Leôncio",
    "Leonel",
    "Leónidas",
    "Leopoldo",
    "Lineu",
    "Lionel",
    "Lisandro",
    "Lívio",
    "Logan",
    "Luã",
    "Luan",
    "Luca",
    "Luciano",
    "Lúcio",
    "Luigi",
    "Luiz",
    "Lukas",
    "Luzio",
    "Macário",
    "Magnus",
    "Malvino",
    "Manassés",
    "Manoel",
    "Maomé",
    "Márcio",
    "Marcos",
    "Marcus",
    "Marley",
    "Marlon",
    "Martin",
    "Martinho",
    "Marvin",
    "Matheo",
    "Matheus",
    "Mathias",
    "Mathieu",
    "Maurílio",
    "Max",
    "Maximiliano",
    "Maxwell",
    "Mélvin",
    "Messias",
    "Micael",
    "Michael",
    "Michel",
    "Milo",
    "Milton",
    "Mizael",
    "Moacir",
    "Mohamed",
    "Nataniel",
    "Nazário",
    "Neil",
    "Nereu",
    "Nestor",
    "Newton",
    "Ney",
    "Nicola",
    "Nicolas",
    "Nildemar",
    "Nilo",
    "Nilson",
    "Nilton",
    "Nivaldo",
    "Nonato",
    "Norberto",
    "Norildo",
    "Norimar",
    "Odemar",
    "Odilson",
    "Odin",
    "Odorico",
    "Olin",
    "Omar",
    "Omer",
    "Onofre",
    "Orestes",
    "Orlandino",
    "Orlando",
    "Osias",
    "Osman",
    "Osmar",
    "Osório",
    "Osvaldo",
    "Otacílio",
    "Otávio",
    "Otto",
    "Ozael",
    "Pablo",
    "Paco",
    "Paolo",
    "Pascoal",
    "Patrício",
    "Patrick",
    "Paulino",
    "Pepe",
    "Percival",
    "Péricles",
    "Pierre",
    "Porfírio",
    "Querubim",
    "Quintino",
    "Radamés",
    "Rafaelo",
    "Raí",
    "Raimundo",
    "Ralf",
    "Ralph",
    "Ramiro",
    "Ramon",
    "Ramón",
    "Raoni",
    "Raphael",
    "Reginaldo",
    "Régis",
    "Reimão",
    "Reinaldo",
    "Renan",
    "Renato",
    "Renê",
    "Rivaldo",
    "Roberto",
    "Robson",
    "Rodney",
    "Rodolfo",
    "Roger",
    "Rogério",
    "Roland",
    "Rolando",
    "Romão",
    "Romário",
    "Romeo",
    "Rômulo",
    "Ronald",
    "Ronaldo",
    "Roni",
    "Rosendo",
    "Rúbens",
    "Rudesindo",
    "Rudolfo",
    "Ruy",
    "Ryan",
    "Sansão",
    "Saúl",
    "Saulo",
    "Sávio",
    "Selton",
    "Sertório",
    "Severino",
    "Sidney",
    "Silas",
    "Sílvio",
    "Simplício",
    "Sinésio",
    "Stefan",
    "Stefano",
    "Stenio",
    "Steve",
    "Steven",
    "Sydney",
    "Taciano",
    "Tadeu",
    "Tales",
    "Tamires",
    "Tâmiris",
    "Tarcísio",
    "Tarik",
    "Tarsício",
    "Telmo",
    "Tenório",
    "Teo",
    "Teobaldo",
    "Teodemiro",
    "Thales",
    "Theo",
    "Thiago",
    "Thomas",
    "Thomaz",
    "Tibúrcio",
    "Ticiano",
    "Tierry",
    "Timóteo",
    "Tito",
    "Tom",
    "Tomaz",
    "Tristão",
    "Troy",
    "Túlio",
    "Ubirajara",
    "Ubiratã",
    "Urbano",
    "Uriel",
    "Valdemar",
    "Valentino",
    "Vanderlei",
    "Vasco",
    "Venâncio",
    "Veríssimo",
    "Vicenzo",
    "Victor",
    "Vílmar",
    "Vilson",
    "Vinícius",
    "Virgílio",
    "Vital",
    "Vítor",
    "Vladimir",
    "Wagner",
    "Waldir",
    "Waldo",
    "Wallace",
    "Walter",
    "Washington",
    "Watson",
    "Webster",
    "Weller",
    "Wellington",
    "Wendel",
    "Wesley",
    "Will",
    "William",
    "Wilson",]
NOMES2 = [
    "ALMEIDA", 
    "ALVES",     
    "ANDRADE", 
    "BARBOSA", 
    "BARROS", 
    "BATISTA", 
    "BORGES", 
    "CAMPOS", 
    "CARDOSO",
    "CARVALHO", 
    "CASTRO",
    "COSTA", 
    "DIAS", 
    "DUARTE", 
    "FREITAS",
    "FERNANDES", 
    "FERREIRA", 
    "GARCIA", 
    "GOMES", 
    "GONÇALVES", 
    "LIMA", 
    "LOPES", 
    "MACHADO", 
    "MARQUES", 
    "MARTINS", 
    "MEDEIROS",
    "MELO",
    "MENDES",
    "MIRANDA", 
    "MONTEIRO",
    "MORAES", 
    "MOREIRA", 
    "MOURA", 
    "NASCIMENTO", 
    "NUNES", 
    "OLIVEIRA", 
    "PEREIRA", 
    "RAMOS", 
    "REIS", 
    "RIBEIRO", 
    "ROCHA",
    "SANTANA", 
    "SANTOS", 
    "SILVA", 
    "SOARES", 
    "SOUZA",
    "TEIXEIRA", 
    "VIEIRA",]
estado2 = [
    "Acre", 
    "Alagoas", 
    "Amapá", 
    "Amazonas", 
    "Bahia", 
    "Ceará", 
    "Distrito Federal", 
    "Espírito Santo", 
    "Goiás", 
    "Maranhão", 
    "Mato Grosso", 
    "Mato Grosso do Sul", 
    "Minas Gerais", "Pará", 
    "Paraíba", 
    "Paraná", 
    "Pernambuco", 
    "Piauí", 
    "Rio de Janeiro", 
    "Rio Grande do Norte",
    "Rio Grande do Sul", 
    "Rondônia", "Roraima", 
    "Santa Catarina",
    "São Paulo", 
    "Sergipe",
    "Tocantins",]

nume = random.randrange(1, 9999999999999999)
cvv = random.randint(100, 999)
data1 = random.randrange(1, 31)
data2 = random.randrange(1, 12)
data3 = random.choice(list)
cpf = random.randrange(11111111111, 99999999999)
nome = random.choice(NOMES)
sobrenome = random.choice(NOMES2)

data8 = random.randrange(1, 31)
data9 = random.randrange(1, 12)
data0 = random.choice(list2)
estado = random.choice(estado2)

bi = str(input('Você deseja continua e aceita o termo de uso ? s ou n?: '))

if bi == 's':
    os.system("clear")
    os.system ("toilet -f big 'GERANDO' -F gay | lolcat")
    time.sleep(4)
    print('Número do cartão',nume)
    print('CVV do cartão:',cvv)
    print('Data do cartão:', data1, data2, data3)
    print('CPF cadastrado no cartão:', cpf)
    print('NOME DA PESSOA:', nome, sobrenome)
    print('DATA DE NASCIMENTO:', data8, data9, data0)
    print('ESTADO:', estado)
    print("\033[31;1m >>>>---------------------<<<< \033[32;1m")
    print("\033[31;1m >>>>VOLTE SEMPRE MESTRE<<<< \033[32;1m")
    
else:
    time.sleep(1)
    
    print("\033[33;1m não é possivel iniciar a ferramenta. (termo de uso negado!!!) \033[32;1m")
